from typing import Protocol

from binance50.connectors.capabilities import ConnectorCapabilities
from binance50.connectors.response_models import ConnectorHealth
from binance50.core.enums import AccountDomain, EnvironmentProfileName, ExchangeName, MarketScope


# We'll use a placeholder for EndpointInfo to avoid circular import if needed,
# or just import it after creating endpoint_resolver
class EndpointInfoProtocol(Protocol):
    rest_base_url: str | None
    is_testnet: bool
    is_mainnet: bool
    is_paper: bool


class RestConnectorProtocol(Protocol):
    def is_enabled(self) -> bool: ...
    def get_capabilities(self) -> ConnectorCapabilities: ...
    def get_endpoint_info(self) -> EndpointInfoProtocol: ...
    def ping(self) -> ConnectorHealth: ...
    def close(self) -> None: ...


class WebSocketConnectorProtocol(Protocol):
    def is_enabled(self) -> bool: ...
    def get_capabilities(self) -> ConnectorCapabilities: ...
    def build_stream_url(self, streams: list[str], combined: bool = True) -> str: ...
    def connect(self) -> None: ...
    def close(self) -> None: ...


class ExchangeAdapterProtocol(Protocol):
    @property
    def exchange_name(self) -> ExchangeName: ...
    @property
    def account_domain(self) -> AccountDomain: ...
    @property
    def market_scope(self) -> MarketScope: ...
    @property
    def environment_profile(self) -> EnvironmentProfileName: ...

    @property
    def rest(self) -> RestConnectorProtocol: ...
    @property
    def websocket(self) -> WebSocketConnectorProtocol: ...

    def get_health(self) -> ConnectorHealth: ...


class ConnectorLifecycleProtocol(Protocol):
    def startup(self) -> None: ...
    def shutdown(self) -> None: ...
