from pathlib import Path

file_path = Path("src/binance50/core/error_codes.py")
content = file_path.read_text()

error_codes = """
# Phase 11 Indicator Error Codes
INDICATOR_CONFIG_INVALID = "INDICATOR_CONFIG_INVALID"
INDICATOR_INPUT_INVALID = "INDICATOR_INPUT_INVALID"
INDICATOR_VALIDATION_FAILED = "INDICATOR_VALIDATION_FAILED"
INDICATOR_COMPUTATION_FAILED = "INDICATOR_COMPUTATION_FAILED"
INDICATOR_REGISTRY_FAILED = "INDICATOR_REGISTRY_FAILED"
INDICATOR_BACKEND_FAILED = "INDICATOR_BACKEND_FAILED"
OPTIONAL_INDICATOR_BACKEND_MISSING = "OPTIONAL_INDICATOR_BACKEND_MISSING"
INDICATOR_QUALITY_FAILED = "INDICATOR_QUALITY_FAILED"
INDICATOR_CACHE_FAILED = "INDICATOR_CACHE_FAILED"
LOOKAHEAD_BIAS_DETECTED = "LOOKAHEAD_BIAS_DETECTED"
INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
WARMUP_FAILED = "WARMUP_FAILED"
"""

if "INDICATOR_CONFIG_INVALID" not in content:
    content += "\n" + error_codes

file_path.write_text(content)
print("Patched error codes")
