with open("binance50/src/binance50/core/error_codes.py", "r") as f:
    content = f.read()

error_codes = """
ML_DATASET_CONFIG_INVALID = "ML_DATASET_CONFIG_INVALID"
ML_FEATURE_SOURCE_FAILED = "ML_FEATURE_SOURCE_FAILED"
ML_FEATURE_SELECTION_FAILED = "ML_FEATURE_SELECTION_FAILED"
ML_LABEL_FAILED = "ML_LABEL_FAILED"
ML_LABEL_SPEC_INVALID = "ML_LABEL_SPEC_INVALID"
ML_SPLIT_FAILED = "ML_SPLIT_FAILED"
ML_PREPROCESSING_FAILED = "ML_PREPROCESSING_FAILED"
ML_SCALER_FAILED = "ML_SCALER_FAILED"
ML_ALIGNMENT_FAILED = "ML_ALIGNMENT_FAILED"
ML_LEAKAGE_DETECTED = "ML_LEAKAGE_DETECTED"
ML_DATASET_QUALITY_FAILED = "ML_DATASET_QUALITY_FAILED"
ML_DATASET_REGISTRY_FAILED = "ML_DATASET_REGISTRY_FAILED"
ML_DATASET_CACHE_FAILED = "ML_DATASET_CACHE_FAILED"
ML_DATASET_EXPORT_FAILED = "ML_DATASET_EXPORT_FAILED"
"""

content += error_codes

with open("binance50/src/binance50/core/error_codes.py", "w") as f:
    f.write(content)
