with open('binance50/src/binance50/core/error_codes.py', 'r') as f:
    content = f.read()

storage_codes = """
# Phase 10 Storage Error Codes
STORAGE_CONFIG_INVALID = "STORAGE_CONFIG_INVALID"
STORAGE_PATH_INVALID = "STORAGE_PATH_INVALID"
STORAGE_SCHEMA_INVALID = "STORAGE_SCHEMA_INVALID"
STORAGE_CATALOG_FAILED = "STORAGE_CATALOG_FAILED"
STORAGE_MIGRATION_FAILED = "STORAGE_MIGRATION_FAILED"
STORAGE_INTEGRITY_FAILED = "STORAGE_INTEGRITY_FAILED"
STORAGE_MANIFEST_INVALID = "STORAGE_MANIFEST_INVALID"
STORAGE_PARTITION_INVALID = "STORAGE_PARTITION_INVALID"
STORAGE_BACKUP_FAILED = "STORAGE_BACKUP_FAILED"
STORAGE_RETENTION_FAILED = "STORAGE_RETENTION_FAILED"
STORAGE_LOCK_FAILED = "STORAGE_LOCK_FAILED"
DATASET_REGISTRY_FAILED = "DATASET_REGISTRY_FAILED"
DATA_INDEX_FAILED = "DATA_INDEX_FAILED"
QUALITY_INDEX_FAILED = "QUALITY_INDEX_FAILED"
PARQUET_WRITE_FAILED = "PARQUET_WRITE_FAILED"
PARQUET_READ_FAILED = "PARQUET_READ_FAILED"
SQLITE_CATALOG_FAILED = "SQLITE_CATALOG_FAILED"
DESTRUCTIVE_ACTION_BLOCKED = "DESTRUCTIVE_ACTION_BLOCKED"
"""

with open('binance50/src/binance50/core/error_codes.py', 'w') as f:
    f.write(content + "\n" + storage_codes)
