with open("binance50/src/binance50/core/error_codes.py", "r") as f:
    content = f.read()

new_codes = """
# Phase 9 Stream Error Codes
STREAM_REAL_CONNECT_DISABLED = "STREAM_REAL_CONNECT_DISABLED"
STREAM_CONFIG_INVALID = "STREAM_CONFIG_INVALID"
STREAM_SUBSCRIPTION_INVALID = "STREAM_SUBSCRIPTION_INVALID"
STREAM_PARSE_FAILED = "STREAM_PARSE_FAILED"
STREAM_VALIDATION_FAILED = "STREAM_VALIDATION_FAILED"
STREAM_BUFFER_OVERFLOW = "STREAM_BUFFER_OVERFLOW"
STREAM_DUPLICATE_EVENT = "STREAM_DUPLICATE_EVENT"
STREAM_STALE_EVENT = "STREAM_STALE_EVENT"
STREAM_OUT_OF_ORDER = "STREAM_OUT_OF_ORDER"
STREAM_REPLAY_FAILED = "STREAM_REPLAY_FAILED"
STREAM_ROUTE_INVALID = "STREAM_ROUTE_INVALID"
STREAM_LIFECYCLE_INVALID = "STREAM_LIFECYCLE_INVALID"
REALTIME_STORE_FAILED = "REALTIME_STORE_FAILED"
"""

if "STREAM_REAL_CONNECT_DISABLED" not in content:
    with open("binance50/src/binance50/core/error_codes.py", "w") as f:
        f.write(content.rstrip() + "\n" + new_codes)
