from typing import Any

from binance50.config.models import AppConfig
from binance50.strategies.models import (
    SignalCandidate,
    StrategyConditionEvidence,
    StrategyDirection,
    StrategyExplanation,
)


def build_explanation_summary(
    plugin_name: str, direction: StrategyDirection, evidence: list[StrategyConditionEvidence]
) -> str:
    passed = [e.feature_name for e in evidence if e.passed]
    failed = [e.feature_name for e in evidence if not e.passed]

    msg = f"Candidate generated by {plugin_name}. "
    msg += f"Suggested Direction: {direction}. "
    if passed:
        msg += f"Passed conditions: {', '.join(passed)}. "
    if failed:
        msg += f"Failed conditions: {', '.join(failed)}."

    return msg.strip()


def build_human_readable_explanation(candidate: SignalCandidate) -> str:
    # Intentionally avoiding order-like language
    lines = []
    lines.append(f"Analysis for {candidate.symbol} on {candidate.interval} timeframe:")
    lines.append(f"- Evaluated by plugin: {candidate.plugin_name} ({candidate.plugin_type.value})")
    lines.append(f"- Market indication: {candidate.direction.value.upper()} candidate")
    lines.append(
        f"- Assessed strength: {candidate.strength.value} (Confidence: {candidate.confidence:.1f}%)"
    )
    lines.append(f"- Expiry bounds: {candidate.expiry_bars} bars")

    if candidate.explanation and candidate.explanation.evidence:
        lines.append("- Condition Evidence:")
        for e in candidate.explanation.evidence:
            status = "PASS" if e.passed else "FAIL"
            actual = e.actual_value if e.actual_value is not None else "N/A"
            thresh = e.threshold if e.threshold is not None else "N/A"
            if isinstance(actual, float):
                actual = f"{actual:.4f}"
            if isinstance(thresh, float):
                thresh = f"{thresh:.4f}"

            lines.append(
                f"  * [{status}] {e.feature_name} {e.operator} {thresh} (Actual: {actual})"
            )

    if candidate.rejection_reasons:
        lines.append(
            f"- Rejection Reasons: {', '.join([r.value for r in candidate.rejection_reasons])}"
        )

    return "\n".join(lines)


def build_machine_readable_explanation(evidence: list[StrategyConditionEvidence]) -> dict[str, Any]:
    return {
        "evidence_count": len(evidence),
        "passed_count": len([e for e in evidence if e.passed]),
        "failed_count": len([e for e in evidence if not e.passed]),
        "details": [e.model_dump() for e in evidence],
    }


def summarize_evidence(evidence: list[StrategyConditionEvidence]) -> dict[str, Any]:
    return {
        "passed": [e.feature_name for e in evidence if e.passed],
        "failed": [e.feature_name for e in evidence if not e.passed],
    }


def validate_explanation(explanation: StrategyExplanation, config: AppConfig) -> None:
    from binance50.strategies.validators import detect_order_like_language

    if detect_order_like_language(explanation.summary):
        raise ValueError("Explanation summary contains actionable order language")
    if detect_order_like_language(explanation.human_readable):
        raise ValueError("Explanation human readable text contains actionable order language")
