from typing import Any, Protocol

import pandas as pd


class RegimeModelAdapter(Protocol):
    def name(self) -> str: ...

    def is_available(self) -> bool: ...

    def availability_report(self) -> dict[str, Any]: ...

    def fit(self, train_df: pd.DataFrame, feature_columns: list[str]) -> None: ...

    def predict(self, df: pd.DataFrame) -> pd.Series: ...

    def predict_proba(self, df: pd.DataFrame) -> pd.DataFrame | None: ...

    def map_clusters_to_regimes(self, df: pd.DataFrame, labels: pd.Series) -> dict[int, str]: ...

    def save_model(self, path: str) -> None: ...

    def load_model(self, path: str) -> None: ...
